var gfc_pm=osapi,gfc_qm="ceil";gfc_2[gfc_].share=gfc_Uc(24,function(){gfc_$l();return gfc_d});gfc_Ff[gfc_].ceil=gfc_Uc(20,function(){gfc_qa(this,gfc_l[gfc_qm](this[gfc_q]));gfc_La(this,gfc_l[gfc_qm](this[gfc_M]));return this});gfc_2[gfc_].Ri=gfc_Uc(19,function(){var a=this.Gd;if(a.valid){this.d=this.Og(this.Gd);this.Wh(a[gfc_Kb])}else{this.Gd=gfc_c;this.render(a.actions,a[gfc_Kb],a.params)}this.Ng()});gfc_2[gfc_].Qf=gfc_Uc(14,function(){return this.Hb.pop()});
gfc_2[gfc_].ui=gfc_Uc(5,function(a,b,c){return a?c<b?[]:a[gfc_bb](gfc_l.min(b,a[gfc_o]),gfc_l.min(c,a[gfc_o])):[]});
var gfc_rm=function(a){return a=gfc_i.friendconnect_serverBase+"/friendconnect/favicon?url="+escape(a)},gfc_7=function(a,b,c){this.Ia();this.ur();var d=new gfc_R;d.set("members",{action:this.Ou,callback:this.Ht});d.set("member-page",{action:this.Nu,callback:this.Gt});d.set("blocked-member-page",{action:this.Hu,callback:this.Ct});d.set("profile-friends-page",{action:this.Tu,callback:this.Lt});d.set("sitesData",{action:this.av,callback:this.Pt});d.set("viewerFriends",{action:this.fv,callback:this.Rt});
d.set("profileData",{action:this.Su,callback:this.Kt});d.set("blockUser",{action:this.Gu,callback:this.Bt});d.set("unblockUser",{action:this.dv,callback:this.Qt});d.set("profileFriends",{action:this.Uu,callback:this.Mt});d.set("activityData",{action:this.Yf,callback:this.pd});d.set("sendFriendRequest",{action:this.$u,callback:this.Ot});d.set("sendFriendRequestResponse",{action:this.Ku,callback:this.um});d.set("deleteActivity",{action:this.Zf,callback:this.pd});d.set("requestAndProcessViewerNumWaitingMessages",
{action:this.gv,callback:this.Tt});d.set("requestPromo",{action:this.Vu,callback:this.Nt});this.lb=gfc_c;this.xx=new gfc_hm("fc-members-options-menu",gfc_O(this.ft,this),gfc_O(this.et,this),gfc_O(this.gt,this),0,gfc_i.friendconnect_serverBase,this.f("ENDCAP_LINK_COLOR")||"0000cc",this.f("CONTENT_TEXT_COLOR")||"000000");this.mw=gfc_d;this.Fa=10;this.Kf=15;this.xn=10;var e=gfc_Bg(gfc_ng()),f=gfc_sm;this.Zb=3;this.qc=8;this.Um=gfc_c;this.sa=this.qc*this.Zb;this.slimTopCapHeight=19;this.tinyTopCapHeight=
8;this.isMessagingEnabled=a;this.isPromosEnabled=b;this.isSocialShareEnabled=c;this.numWaitingMessages=0;this.promoCode=-1;this.promoHtml=gfc_c;this.Rb=new gfc_dm;if(this.Qh()){a=(a=this.f(f.FACE_SIZE))?gfc_fa(a):32;a=a+6;this.Zb=gfc_l[gfc_ib]((e[gfc_q]-10)/a);e=340;e=this.f(f.HEIGHT);b=this.f(f.NUMBER_ROWS);f=27;if(b){this.qc=gfc_fa(b);e=this.qc*a;this.Um=e+f}else if(e){e=gfc_fa(e)-96;this.qc=gfc_l.max(2,gfc_l[gfc_ib](e/a));this.Um=this.qc*a+f}this.sa=this.qc*this.Zb}gfc_2[gfc_D](this,d)};gfc_7.inherits(gfc_2);
gfc_Ba(gfc_7[gfc_],function(){gfc_7.i[gfc_F][gfc_D](this);gfc_Ml("start");var a=gfc_e[gfc_p][gfc_Nb](),b=gfc_ja();if(a=b.profileId||a.profileId){b={};b[gfc_j[gfc_v][gfc_K].ID]=a;a=new gfc_j[gfc_v](b);this.render(["profileData","profileFriends","activityData"],"profile",{person:a})}else{a=["members","viewerFriends"];this.isMessagingEnabled&&a[gfc_n]("requestAndProcessViewerNumWaitingMessages");this.isPromosEnabled&&!this.Nb()&&a[gfc_n]("requestPromo");this.render(a,"faces")}});gfc_7[gfc_].e={};
gfc_7[gfc_].Ia=function(){this.e.MSG_SITE_MEMBERS="Membri";this.e.MSG_BE_THE_FIRST="Sii il primo!";this.e.MSG_NO_SITE_MEMBERS="Ancora nessun membro presente.";this.e.MSG_ALL_SITE_MEMBERS="Tutti i membri";this.e.MSG_ALL_BLOCKED_MEMBERS="Tutti i membri bloccati";this.e.MSG_NO_BLOCKED_MEMBERS="Non hai bloccato alcun membro";this.e.MSG_YOUR_FRIENDS="I tuoi amici";this.e.MSG_ALL_YOUR_FRIENDS="Tutti i tuoi amici";this.e.MSG_JFJ="Unisciti e comunica con gli altri";this.e.MSG_MANAGE="Gestisci membri";this.e.MSG_SETTINGS=
"Impostazioni";this.e.MSG_OPTIONS="Opzioni";this.e.MSG_INVITE="Invita";this.e.MSG_MEMBERS_SHARE="Condividi questa pagina";this.e.MSG_BACK="Indietro";this.e.MSG_BACK_TO_TOP="Home page";this.e.MSG_VIEW_MY_PROFILE="Visualizza il mio profilo";this.e.MSG_ABOUT_ME="Informazioni su di me";this.e.MSG_MORE="Altro \u00bb";this.e.MSG_SHOW_BLOCKED="Mostra membri bloccati \u00bb";this.e.MSG_SHOW_ALL="\u00ab Mostra tutti i membri";this.e.MSG_INVITE_YOUR_FRIENDS="Invita i tuoi amici";this.e.MSG_LINK_IN_NETWORKS=
"Collegati ai tuoi social network";this.e.MSG_ACTIVITIES="Attivit\u00e0";this.e.MSG_ALL_ACTIVITIES="Altre attivit\u00e0";this.e.MSG_DELETE_THIS="Elimina";this.e.MSG_SITES="Siti a cui mi sono unito";this.e.MSG_ALL_SITES="Altri siti a cui mi sono unito";this.e.MSG_LINKS="Link";this.e.MSG_ALL_LINKS="Altri link";this.e.MSG_NO_ACTIVITIES="Nessuna attivit\u00e0 da visualizzare";this.e.MSG_ADD_AS_FRIEND="Aggiungi come amico";this.e.MSG_SEND_MESSAGE="Invia un messaggio";this.e.MSG_BLOCK_USER="Blocca questo utente";
this.e.MSG_UNBLOCK_USER="Sblocca questo utente";this.e.MSG_USER_IS_ADMIN="Amministratore";this.e.MSG_JOIN="Unisciti a questo sito";this.e.MSG_OR="oppure";this.e.MSG_SIGN_IN="Accedi";this.e.MSG_SIGN_OUT="Esci";this.e.MSG_PREVIOUS="\u00ab Precedente";this.e.MSG_NEXT="Avanti \u00bb";this.e.MSG_NEWER="\u00ab Pi\u00f9 recenti";this.e.MSG_OLDER="Vecchi \u00bb";this.e.MSG_ACCEPT_ALL_FRIEND_REQUESTS="Accetta tutto";this.e.MSG_HELP_FRIENDREQUEST="Potrai rimanere in contatto con i tuoi amici su tutti i siti Friend Connect.";
this.e.MSG_HELP_FRIENDINVITE="Una volta che sarete amici, potrete vedervi su tutti i siti Friend Connect.";this.e.MSG_HELP_BLOCKMEMBER="Se blocchi un visitatore, lo rimuovi dall'elenco membri gli impedisci di interagire con altri visitatori del tuo sito";this.e.MSG_INVITATION="Invito:";this.e.MSG_SEND="Invia";this.e.MSG_BLOCK="Blocca";this.e.MSG_IGNORE="Ignora";this.e.MSG_CANCEL="Annulla";this.e.MSG_SITE_SETTINGS="Impostazioni sito";this.e.MSG_INVITE_FRIENDS="Invita amici";this.e.MSG_ABOUT_FC="Informazioni su Friend Connect";
this.e.MSG_ALREADY_MEMBER="Sei gi\u00e0 un membro?";this.e.MSG_EDIT_PROFILE="Modifica profilo"};gfc_7[gfc_].va={};
gfc_7[gfc_].ur=function(){this.va.MSG_SITE_MEMBERS="Follower";this.va.MSG_NO_SITE_MEMBERS="Non sono presenti follower.";this.va.MSG_SHOW_BLOCKED="Mostra follower bloccati \u00bb";this.va.MSG_SHOW_ALL="\u00ab Mostra tutti i follower";this.va.MSG_ALL_SITE_MEMBERS="Tutti i follower";this.va.MSG_ALL_BLOCKED_MEMBERS="Tutti i follower bloccati";this.va.MSG_NO_BLOCKED_MEMBERS="Non hai bloccato alcun follower";this.va.MSG_LIKE_THIS_SITE="Ti piace questo blog?";this.va.MSG_JOIN="Segui";this.va.MSG_BACK_TO_TOP=
"Membri";this.va.MSG_JFJ="Segui i tuoi amici e mettiti in contatto con loro!";this.va.MSG_HELP_FRIENDREQUEST="Tu e i tuoi amici potrete vedervi su tutti i blog seguiti e i siti Friend Connect.";this.va.MSG_HELP_FRIENDINVITE="Una volta che sarete amici, potrete vedervi in tutti i siti Friend Connect e i blog seguenti."};
gfc_7[gfc_].N=function(a,b){var c=gfc_b;if(b[gfc_G]&&b[gfc_G].person){var d={},e=b[gfc_G].person[gfc_Hb]()+" \u00e8 tuo amico";d.MSG_IS_FRIEND=e;e="Hai invitato "+(b[gfc_G].person[gfc_Hb]()+" come amico");d.MSG_IS_INVITED=e;e="Amici di "+b[gfc_G].person[gfc_Hb]();d.MSG_PROFILE_FRIENDS=e;e="Tutti gli amici di "+b[gfc_G].person[gfc_Hb]();d.MSG_ALL_PROFILE_FRIENDS=e;for(var f in d)this.g(a,f,d[f])}if(b.invitedBy&&b.invitedBy[gfc_Hb]()){d=gfc_k[gfc_q]?gfc_k[gfc_q]:gfc_k[gfc_y][gfc_8a]+2;c=(d-135)/8;d=
(d-175)/8;c="Visualizza il profilo di "+gfc_Al(b.invitedBy[gfc_Hb](),c);d=gfc_Al(b.invitedBy[gfc_Hb](),d)+" ti ha invitato a questo sito";this.g(a,"MSG_VIEW_INVITER_PROFILE",c);this.g(a,"MSG_INVITED_YOU",d);this.mw=gfc_b;c=gfc_d}d=this.numWaitingMessages+" messaggi in attesa.";if(this.isMessagingEnabled&&this.numWaitingMessages>0){c=gfc_d;this.g(a,"showWaitingMessages",gfc_b);if(this.isMessagingEnabled){this.g(a,"MSG_NUM_WAITING_MESSAGES",d);this.g(a,"MSG_VIEW_AND_CONFIGURE_MESSAGING","Visualizza messaggi")}}if(b.friendRequests){if(b.friendRequests[gfc_4a]()>
0)c=gfc_d;if(b.friendRequests[gfc_4a]()==1)d="Nuova richiesta di amicizia \u00bb";else d=d="Nuove richieste di amicizia ("+(b.friendRequests[gfc_4a]()+") \u00bb");this.g(a,"MSG_NEW_FRIEND_REQUESTS",d)}if(this.lb){if(this.tl(this.lb.themeId))for(f in this.va)this.g(a,f,this.va[f]);this.lb.signInPrompt&&this.g(a,"MSG_JOIN",this.lb.signInPrompt);this.lb.signOutPrompt&&this.g(a,"MSG_SIGN_OUT",this.lb.signOutPrompt)}this.g(a,"isViewerAdmin",b.isViewerAdmin);this.g(a,"isMessagingEnabled",this.isMessagingEnabled);
this.g(a,"acceptMessages",this.Yn);this.g(a,"isViewingSelf",b.viewer&&b[gfc_G]&&b[gfc_G].person&&b.viewer[gfc_B]()==b[gfc_G].person[gfc_B]());d=gfc_d;if(b.owner)if(e=b.owner[gfc_L]("profileExtensions"))for(f in e)d=gfc_b;this.g(a,"communityHasProfile",d);this.g(a,"promoHtml",c?this.promoHtml:gfc_c);this.g(a,"insertHtml",function(g,h){gfc_sa(g,h)})};gfc_7[gfc_].tl=function(a){return a=="blogger"};
gfc_7[gfc_].dh=function(a,b,c,d){gfc_8l({id:a,text:b,version:this.tl(this.lb.themeId)?1:gfc_c,style:c},d)};
gfc_7[gfc_].Q=function(a){function b(e,f){d.g(a,e,gfc_O(f,d))}this.g(a,"facesPerRow",this.Zb);for(var c in this.e)this.g(a,c,this.e[c]);var d=this;b("getThumbnail",this.vc);b("map",this.map);b("elide",gfc_Al);b("safeSlice",this.ui);b("showAllActivities",this.Yv);b("transformActivity",this.ic);b("nextActivities",this.Ds);b("previousActivities",this.ot);b("showAllLinks",this.$v);b("transformLink",this.Mw);b("nextLinks",this.Hs);b("previousLinks",this.qt);b("showAllSites",this.cw);b("transformSite",
this.Nw);b("nextSites",this.Os);b("previousSites",this.wt);b("showAllMembers",this.aw);b("showBlockedMembers",this.ew);b("showUnblockedMembers",this.vw);b("nextMembers",this.Is);b("nextBlockedMembers",this.Es);b("previousMembers",this.rt);b("previousBlockedMembers",this.pt);b("showAllProfileFriends",this.bw);b("nextProfileFriends",this.Ns);b("previousProfileFriends",this.vt);b("showAllViewerFriends",this.dw);b("nextViewerFriends",this.Ps);b("previousViewerFriends",this.xt);b("isHome",this.Oh);b("goBack",
this.qh);b("goBackToHome",this.nw);b("invite",this.invite);b("editSettings",this.Bb);b("signout",this.signout);b("signin",this.signin);b("viewProfile",this.On);b("blockUser",this.qj);b("unblockUser",this.Qw);b("goToInviteFriend",this.Fq);b("sendMessageDialog",this.uv);b("goToBlockMember",this.Eq);b("goToEditProfile",this.Bb);b("goToViewerProfile",this.Gq);b("sendInvite",this.tv);b("blockMember",this.to);b("acceptFriendRequest",this.Xn);b("ignoreFriendRequest",this.tr);b("viewFriendRequests",this.$w);
b("acceptAllFriendRequests",this.Wn);b("numPreviewFriends",this.nq);b("numPreviewMembers",this.oq);b("showInvitedBy",this.vq)};
gfc_7[gfc_].Lk=function(a){a=gfc_l.max(1,a?this.qc-1:this.qc);var b=this.d[gfc_s].members?this.d[gfc_s].members[gfc_4a]():0,c=this.d[gfc_s].friends?this.d[gfc_s].friends[gfc_4a]():0;b=gfc_l[gfc_qm](b/this.Zb);c=gfc_l[gfc_qm](c/this.Zb);if(b>gfc_l[gfc_qm](a/2))if(c>gfc_l[gfc_ib](a/2)){b=gfc_l[gfc_qm](a/2);c=gfc_l[gfc_ib](a/2)}else b=gfc_l.max(0,a-c);else if(c>gfc_l[gfc_ib](a/2))c=gfc_l.max(0,a-b);b=b*this.Zb;c=c*this.Zb;return a={numMembers:b,numFriends:c}};gfc_7[gfc_].oq=function(a){return this.Lk(a).numMembers};
gfc_7[gfc_].nq=function(a){return this.Lk(a).numFriends};gfc_7[gfc_].Nu=function(a,b){var c=gfc_j[gfc_J](),d={},e=gfc_j[gfc_z][gfc_ic];d[e.FILTER]="PUBLICLY_VISIBLE";d[e.FIRST]=b[gfc_F];d[e.MAX]=b.pageSize?b.pageSize:this.sa;var f=[gfc_j[gfc_v][gfc_K].ID,gfc_j[gfc_v][gfc_K][gfc_Xa],gfc_j[gfc_v][gfc_K][gfc_Ec]];d[e[gfc_lc]]=f;d[gfc_j[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_j.EscapeType.NONE;c.add(c[gfc_Xb](gfc_Rd(),d),"ownerFriends");c[gfc_E](a)};
gfc_7[gfc_].Gt=function(a){this.d[gfc_s].members=a.get("ownerFriends")[gfc_t]()};gfc_7[gfc_].Hu=function(a,b){var c=gfc_j[gfc_J](),d={},e=gfc_j[gfc_z][gfc_ic];d[e.FIRST]=b[gfc_F];d[e.MAX]=b.pageSize?b.pageSize:this.sa;d[gfc_j[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_j.EscapeType.NONE;e={};e[gfc_j[gfc_Sa][gfc_K][gfc_Fb]]=gfc_j[gfc_Sa].PersonId.OWNER;e[gfc_j[gfc_Sa][gfc_K][gfc_kb]]="BLOCKED";e[gfc_j[gfc_Sa][gfc_K][gfc_Wa]]=1;e=gfc_j[gfc_Mc](e);c.add(c[gfc_Xb](e,d),"blockedMembers");c[gfc_E](a)};
gfc_7[gfc_].Ct=function(a){this.d[gfc_s].blockedMembers=a.get("blockedMembers")[gfc_t]()};gfc_7[gfc_].Tu=function(a,b){var c=gfc_j[gfc_J](),d=b&&b.person&&b.person[gfc_B]()||this.I[gfc_G].person[gfc_B](),e={},f=gfc_j[gfc_z][gfc_ic];e[f.FIRST]=b[gfc_F];e[f.MAX]=b.pageSize?b.pageSize:this.sa;d=this.Zl(d);e[gfc_j[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_j.EscapeType.NONE;c.add(c[gfc_Xb](d,e),"profileFriends");c[gfc_E](a)};
gfc_7[gfc_].Zl=function(a){var b={};b[gfc_j[gfc_Sa][gfc_K][gfc_Fb]]=a;b[gfc_j[gfc_Sa][gfc_K][gfc_kb]]="FRIENDS";b[gfc_j[gfc_Sa][gfc_K][gfc_Wa]]=1;return gfc_j[gfc_Mc](b)};gfc_7[gfc_].Lt=function(a){this.d[gfc_s][gfc_G].friends=a.get("profileFriends")[gfc_t]()};gfc_7[gfc_].ij=function(a){for(var b=gfc_j[gfc_s].getDataContext(),c=0;c<a[gfc_o];c++){var d=a[c];d=b.getDataSet(d);if(!d||d.code)return gfc_d}return gfc_b};
gfc_7[gfc_].Ou=function(a){var b=this.sa,c=!b||b==24;if(c&&gfc_j[gfc_s])if(this.ij(["ownerFriends","viewer","siteSettings","friendRequests"])){a(gfc_j[gfc_s].getDataContext()[gfc_t]());return}c=gfc_pm.newBatch();b={userId:"@owner",groupId:"@friends",count:b,filterBy:"PUBLICLY_VISIBLE"};c.add("ownerFriends",gfc_pm.people.get(b));c.add("viewer",gfc_pm.people.getViewer());c.add("siteSettings",gfc_pm.extensions.get({command:"GetSiteSettings"}));c.add("friendRequests",gfc_pm.extensions.get({command:"GetFriendRequests",
params:'{"idSpec" : "VIEWER"}'}));(b=gfc_ja().psinvite)&&c.add("invitedBy",gfc_pm.extensions.get({command:"DecodeInvitation",params:{token:b}}));c.execute(a)};gfc_7[gfc_].Ht=function(a,b){this.d[gfc_s].members=gfc_Jd(a.ownerFriends,gfc_Ed);this.d[gfc_s].viewer=gfc_Ed(a.viewer);this.um(a,b,gfc_b);this.lb=a[gfc_mc];var c=gfc_ja();if(c.psinvite)if(this.d[gfc_s].viewer==gfc_c||this.d[gfc_s].viewer==""){if(a.invitedBy)a.invitedBy.nickname=a.invitedBy.displayName;this.d[gfc_s].invitedBy=new gfc_j[gfc_v](a.invitedBy)}};
gfc_7[gfc_].fv=function(a,b){b=b||{};var c=b.pageSize||this.maxFacesPerPage,d=!b[gfc_F]||b[gfc_F]==0,e=!c||c==20;if(d&&e&&gfc_j[gfc_s])if(this.ij(["friends","isViewerAdmin"])){a(gfc_j[gfc_s].getDataContext()[gfc_t]());return}d=gfc_pm.newBatch();c={userId:"@viewer",groupId:"@friends",count:c};if(b[gfc_F])c.startIndex=b[gfc_F];d.add("friends",gfc_pm.people.get(c));d.add("isViewerAdmin",gfc_pm.people.get({userId:"@viewer",groupId:"ADMINS"}));d.execute(a)};
gfc_7[gfc_].Rt=function(a){var b=a.friends;if(b&&!b.error)this.d[gfc_s].friends=gfc_Jd(b,gfc_Ed);this.Ym(a)};gfc_7[gfc_].gv=function(a){var b=gfc_j[gfc_J]();b.add(gfc_Hd("VIEWER"),"numWaitingMessages");b[gfc_E](a)};gfc_7[gfc_].Tt=function(a){this.numWaitingMessages=a.get("numWaitingMessages")[gfc_t]().numberOfWaitingMessages};
gfc_7[gfc_].Vu=function(a){this.log("requesting promo");var b=new gfc_e[gfc_Ab];b=b.getLang()+(b[gfc_ec]()?"_"+b[gfc_ec]():"");var c=gfc_j[gfc_J]();c.add(gfc_wd("GetPromo",{hl:b}),"promo");c[gfc_E](a)};gfc_7[gfc_].Nt=function(a){this.log("processing promo");if((a=a.get("promo")[gfc_t]())&&a.promoCode!=-1){this.promoCode=a.promoCode;this.promoHtml=a.promoHtml}};
gfc_7[gfc_].fo=function(){for(var a=function(){this.promoHtml=gfc_c;for(var f=gfc_Of("div","fc-promo-main",gfc_U("peg")),g=0;g<f[gfc_o];g++)gfc_Fg(f[g],gfc_d);this.W();this.log("Dismissing promo "+this.promoCode);f=gfc_j[gfc_J]();f.add(gfc_wd("DismissPromo",{promoCode:this.promoCode}));f[gfc_E](gfc_O(function(){this.log("The promo has been dismissed");this.promoCode=-1},this))},b=gfc_Of("a","fc-promo-dismiss-link",gfc_U("peg")),c=0;c<b[gfc_o];c++){var d=b[c],e="click";gfc_uh(d,e);gfc_oh(d,e,gfc_O(a,
this))}};gfc_7[gfc_].Ym=function(a){var b=a.isViewerAdmin;if(b&&!b.error)this.d[gfc_s].isViewerAdmin=b.list[gfc_o];else if(a.get&&a.get("isViewerAdmin"))if((a=a.get("isViewerAdmin"))&&!a[gfc_wb]())this.d[gfc_s].isViewerAdmin=a[gfc_t]()[gfc_4a]()};gfc_7[gfc_].Wn=function(a){var b=[];a.each(function(c){c={user:c[gfc_L](goog.opensocial.peoplesense.Invite[gfc_K].INVITER)[gfc_B](),action:"ACCEPT"};b[gfc_n](c)});this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_O(this.Lg,this),{friendRequestResponses:b})};
gfc_7[gfc_].nw=function(){this.ja();this.render(["members","viewerFriends"],"faces")};gfc_7[gfc_].Xn=function(a){a={user:a[gfc_B](),action:"ACCEPT"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_O(this.Lg,this),{friendRequestResponses:[a]})};gfc_7[gfc_].$w=function(){this.ja();this.z("friend-requests")};gfc_7[gfc_].On=function(a){if(this.Nb()){this.ja();this.bx(a)}else gfc_td(a[gfc_B]())};
gfc_7[gfc_].bx=function(a){this.render(["profileData","profileFriends","activityData"],"profile",{person:a})};gfc_7[gfc_].av=function(a,b){var c=gfc_j[gfc_J](),d=gfc_j[gfc_z][gfc_ic],e={};e[d.FIRST]=b&&b[gfc_F]?b[gfc_F]:0;var f=this.d[gfc_s][gfc_G].person[gfc_B]();e[d.MAX]=this.xn;c.add(gfc_Od(gfc_j[gfc_Mc]({userId:f}),e),"profileSites");c[gfc_E](a)};gfc_7[gfc_].Pt=function(a){this.d[gfc_s][gfc_G].sites=a.get("profileSites")[gfc_t]()};
gfc_7[gfc_].Su=function(a,b){this.d[gfc_s].profile={};b=b||{};var c=b.person,d={};c=c[gfc_B]();var e=gfc_j[gfc_J](),f=[gfc_j[gfc_v][gfc_K].ID,gfc_j[gfc_v][gfc_K][gfc_Xa],gfc_j[gfc_v][gfc_K][gfc_Ec],gfc_j[gfc_v][gfc_K].ABOUT_ME,gfc_j[gfc_v][gfc_K].URLS,"profileExtensions"],g=gfc_j[gfc_z][gfc_ic];d[g[gfc_lc]]=f;d[gfc_j[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_j.EscapeType.NONE;e.add(e.newFetchPersonRequest(c,d),"profile");e.add(e.newFetchPersonRequest("VIEWER",d),"viewer");e.add(gfc_Md("VIEWER","ADMINS"),
"isViewerAdmin");e.add(e.newFetchPersonRequest("OWNER",d),"owner");this.lb||e.add(gfc_Gd(),"siteSettings");e.add(gfc_Md(c,"ADMINS"),"isAdmin");e.add(gfc_Md(c,"BLOCKED"),"isBlocked");this.isMessagingEnabled&&e.add(gfc_Hd(c),"canMessage");e[gfc_E](a)};
gfc_7[gfc_].Yf=function(a,b){var c=b.person[gfc_B](),d=gfc_j[gfc_Mc]({userId:c}),e=gfc_j[gfc_J]();if(this.d[gfc_s].viewer&&c!=this.d[gfc_s].viewer[gfc_B]()||this.Nb())e.add(gfc_Ld(b.person[gfc_B](),"VIEWER"),"isProfileFriend");e.add(e[gfc_tb](d,{}),"activities");e[gfc_E](a)};
gfc_7[gfc_].pd=function(a,b){if(a.get("activities")[gfc_t]()!=gfc_c)this.d[gfc_s][gfc_G].activities=a.get("activities")[gfc_t]();var c=a.get("isProfileFriend");if(c)if(b&&this.d[gfc_s].viewer!=gfc_c&&this.d[gfc_s].viewer[gfc_B]()!=b.person[gfc_B]())this.d[gfc_s][gfc_G].isFriend=c[gfc_t]()[gfc_u]};
gfc_7[gfc_].Kt=function(a,b){var c=a.get("profile")[gfc_t]();this.d[gfc_s][gfc_G].person=c;this.d[gfc_s][gfc_G].person.externalProfileUrl=gfc_c;var d=c[gfc_L](gfc_j[gfc_v][gfc_K].URLS),e=[];if(d)for(var f=0;f<d[gfc_o];f++){var g=d[f];g[gfc_L](gfc_j.Url[gfc_K].TYPE)!="profile"&&g[gfc_L](gfc_j.Url[gfc_K].TYPE)!="externalProfile"&&e[gfc_n](g);if(g[gfc_L](gfc_j.Url[gfc_K].TYPE)=="externalProfile")this.d[gfc_s][gfc_G].person.externalProfileUrl=g[gfc_L](gfc_j.Url[gfc_K].ADDRESS)}this.d[gfc_s][gfc_G].links=
new gfc_tm(e,this.Kf,0);this.d[gfc_s].owner=a.get("owner")[gfc_t]();this.d[gfc_s].viewer=a.get("viewer")[gfc_t]();if((d=this.d[gfc_s].viewer)&&b.person[gfc_B]()!=this.d[gfc_s].viewer[gfc_B]()){this.d[gfc_s][gfc_G].isAdmin=a.get("isAdmin")[gfc_t]();if(this.d[gfc_s][gfc_G].isAdmin)this.d[gfc_s][gfc_G].isAdmin=this.d[gfc_s][gfc_G].isAdmin[gfc_4a]();this.d[gfc_s][gfc_G].isBlocked=a.get("isBlocked")[gfc_t]();if(this.d[gfc_s][gfc_G].isBlocked)this.d[gfc_s][gfc_G].isBlocked=this.d[gfc_s][gfc_G].isBlocked[gfc_4a]()}c=
c[gfc_L]("profileExtensions");c=this.Rb.Cf(c,this.Rb.Ji);d=[];for(f in c){e=c[f];g={};g.title=e.title;var h=gfc_d;if(e.entryType=="SHORT_TEXT"||e.entryType=="LONG_TEXT"){if(e[gfc_u]&&e[gfc_u][gfc_7a]){g.body=[];g[gfc_y][gfc_n](e[gfc_u][gfc_7a]);h=gfc_b}}else if(e[gfc_u]&&e[gfc_u].choice&&e[gfc_u].choice[gfc_o]>0){g.body=[];for(h=0;h<e[gfc_u].choice[gfc_o];++h)g[gfc_y][gfc_n](e[gfc_u].choice[h][gfc_Ac]);h=gfc_b}h&&d[gfc_n](g)}this.d[gfc_s][gfc_G].profileExtensions=d;if(!this.lb)this.lb=a.get("siteSettings")[gfc_t]();
if(this.isMessagingEnabled){f=(f=a.get("canMessage"))&&f[gfc_t]().canSendMessage;this.d[gfc_s][gfc_G].canSendMessage=f}this.Ym(a)};gfc_7[gfc_].qj=function(a){this.render(["blockUser"],"profile",{person:a})};gfc_7[gfc_].Qw=function(a){this.render(["unblockUser"],"profile",{person:a})};gfc_7[gfc_].map=function(a,b){var c=[],d=gfc_O(function(e,f,g){e[gfc_n](f(g))},this,c,b);a.each(d);return c};gfc_7[gfc_].aw=function(){this.ja();this.z("members-page")};
gfc_7[gfc_].ew=function(){this.ja();this.render(["blocked-member-page"],"blocked-members-page",{start:0})};gfc_7[gfc_].vw=function(){this.Ri()};gfc_7[gfc_].Is=function(a){this.render(["member-page"],"members-page",{start:this.sa+a.getOffset()})};gfc_7[gfc_].rt=function(a){this.render(["member-page"],"members-page",{start:a.getOffset()-this.sa})};gfc_7[gfc_].Es=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:this.sa+a.getOffset()})};
gfc_7[gfc_].pt=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:a.getOffset()-this.sa})};gfc_7[gfc_].dw=function(){this.ja();this.z("viewer-friends-page")};gfc_7[gfc_].Ps=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:this.sa+a.getOffset()})};gfc_7[gfc_].xt=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:a.getOffset()-this.sa})};gfc_7[gfc_].bw=function(){this.ja();this.z("profile-friends-page")};
gfc_7[gfc_].Ns=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:this.sa+a.getOffset(),person:this.d[gfc_s][gfc_G].person})};gfc_7[gfc_].vt=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:a.getOffset()-this.sa,person:this.d[gfc_s][gfc_G].person})};gfc_7[gfc_].$v=function(){this.ja();this.z("links")};gfc_7[gfc_].Hs=function(a){var b=this.Kf+a.getOffset();this.d[gfc_s][gfc_G].links=new gfc_tm(a.all(),this.Kf,b);this.z("links")};
gfc_7[gfc_].qt=function(a){var b=a.getOffset()-this.Kf;this.d[gfc_s][gfc_G].links=new gfc_tm(a.all(),this.Kf,b);this.z("links")};gfc_7[gfc_].cw=function(){this.ja();this.z("sites")};gfc_7[gfc_].Os=function(a){this.render(["sitesData"],"sites",{start:this.xn+a.getOffset()})};gfc_7[gfc_].wt=function(a){this.render(["sitesData"],"sites",{start:a.getOffset()-this.xn})};gfc_7[gfc_].Yv=function(){this.ja();this.z("activities")};
gfc_7[gfc_].Ds=function(a){this.render(["activityData"],"activities",{start:this.Fa+a.getOffset()})};gfc_7[gfc_].ot=function(a){this.render(["activityData"],"activities",{start:a.getOffset()-this.Fa})};gfc_7[gfc_].qf=function(a){this.render(["deleteActivity"],this.d[gfc_Kb],{activity:a})};gfc_7[gfc_].Gu=function(a,b){var c=gfc_j[gfc_J]();c.add(gfc_Nd(b.person[gfc_B](),["BLOCKED"],[]),"block");this.kd();c[gfc_E](a)};
gfc_7[gfc_].Bt=function(a){if(a=!a.get("block")[gfc_wb]())this.d[gfc_s][gfc_G].isBlocked=gfc_b};gfc_7[gfc_].dv=function(a,b){var c=gfc_j[gfc_J]();c.add(gfc_Nd(b.person[gfc_B](),[],["BLOCKED"]),"unblock");this.kd();c[gfc_E](a)};gfc_7[gfc_].Qt=function(a){if(a=!a.get("unblock")[gfc_wb]())this.d[gfc_s][gfc_G].isBlocked=gfc_d};
gfc_7[gfc_].Zf=function(a,b){var c=b.activity,d=c[gfc_L](gfc_j[gfc_Zb][gfc_K].ID);c=gfc_j[gfc_Mc]({userId:c[gfc_L](gfc_j[gfc_Zb][gfc_K][gfc_Fb])});var e=gfc_j[gfc_J]();e.add(gfc_xd(d),"delete");e.add(e[gfc_tb](c,{}),"activities");e[gfc_E](a)};
gfc_7[gfc_].ic=function(a){var b=gfc_gm,c=function(f){return f=f[gfc_r](/<a/g,"<a target='_top'")},d=gfc_c,e=this.d[gfc_s].viewer;if(e!=gfc_c&&a[gfc_L](gfc_j[gfc_Zb][gfc_K][gfc_Fb])==this.d[gfc_s].viewer[gfc_B]())d=gfc_O(this.qf,this,a);(e=a[gfc_L](gfc_j[gfc_Zb][gfc_K].STREAM_FAVICON_URL,{escapeType:"none"}))||(e=gfc_i.friendconnect_imageUrl+"/favicons.gif");return{icon:e,time:b(gfc_fa(a[gfc_L](gfc_j[gfc_Zb][gfc_K].POSTED_TIME))),link:a[gfc_L](gfc_j[gfc_Zb][gfc_K].STREAM_URL,{escapeType:"none"}),
siteTitle:a[gfc_L](gfc_j[gfc_Zb][gfc_K].STREAM_TITLE,{escapeType:"none"}),innerHTML:c(a[gfc_L](gfc_j[gfc_Zb][gfc_K].TITLE,{escapeType:"none"})),body:c(a[gfc_L](gfc_j[gfc_Zb][gfc_K].BODY,{escapeType:"none"})),deleteHandler:d}};gfc_7[gfc_].Nw=function(a){var b=gfc_e[gfc_hc].unescapeString,c=gfc_rm;return{icon:c(a[gfc_L](gfc_j[gfc_v][gfc_K][gfc_5b])),link:a[gfc_L](gfc_j[gfc_v][gfc_K][gfc_5b]),title:b(a[gfc_Hb]())}};
gfc_7[gfc_].Mw=function(a){var b=gfc_e[gfc_hc].unescapeString,c=gfc_rm,d=a[gfc_L](gfc_j.Url[gfc_K].ADDRESS);return{icon:c(d),link:d,title:b(a[gfc_L](gfc_j.Url[gfc_K].LINK_TEXT))||d}};
gfc_7[gfc_].Uu=function(a,b){var c=gfc_j[gfc_J](),d=b.person[gfc_B](),e={},f=gfc_j[gfc_z][gfc_ic];e[f[gfc_lc]]=[gfc_j[gfc_v][gfc_K].ID,gfc_j[gfc_v][gfc_K][gfc_Xa]];var g=this.Zl(d),h={};h[gfc_j[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_j.EscapeType.NONE;c.add(c[gfc_Xb](g,h),"friends");g={};g[f.FIRST]=this.ay;g[f.MAX]=this.$x;c.add(gfc_Od(gfc_j[gfc_Mc]({userId:d}),g),"profileSites");e[f[gfc_lc]]=[gfc_j[gfc_v][gfc_K].ID,gfc_j[gfc_v][gfc_K][gfc_Xa],gfc_j[gfc_v][gfc_K][gfc_Ec],gfc_j[gfc_v][gfc_K].ABOUT_ME];
e[gfc_j[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_j.EscapeType.NONE;c[gfc_E](a)};gfc_7[gfc_].tr=function(a){a={user:a[gfc_B](),action:"DENY"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_O(this.Lg,this),{friendRequestResponses:[a]})};gfc_7[gfc_].Lg=function(a){return a&&a["next-view"]?a["next-view"]:["friend-requests"]};gfc_7[gfc_].$u=function(a,b){var c=b[gfc_G],d=gfc_j[gfc_J]();d.add(gfc_yd(c[gfc_B](),b[gfc_Cb]),"friendRequest");this.kd();d[gfc_E](a)};
gfc_7[gfc_].Ot=function(a){if(!a.get("friendRequest")[gfc_wb]())this.d[gfc_s][gfc_G].isInvited=gfc_b};gfc_7[gfc_].Ku=function(a,b){var c=gfc_pm.newBatch(),d=b.friendRequestResponses;c.add("updateFriendRequest",gfc_pm.extensions.get({command:"ProcessFriendRequests",params:'{"requests":'+gfc_e[gfc_2b].stringify(d)+"}"}));c.add("friendRequests",gfc_pm.extensions.get({command:"GetFriendRequests",params:'{"idSpec" : "VIEWER"}'}));this.kd();c.execute(a)};gfc_7[gfc_].Fq=function(){this.ja();this.z("invite-friend")};
gfc_7[gfc_].uv=function(a){if(this.isMessagingEnabled){a=a[gfc_L](gfc_j[gfc_v][gfc_K].ID);this.vv(a)}};gfc_7[gfc_].vv=function(a){if(this.isMessagingEnabled){a="/friendconnect/messaging/compose?recipientId="+a;var b=570,c=395;gfc_0l(a,gfc_h(b),gfc_h(c))}};gfc_2[gfc_].Yn=function(){var a="/friendconnect/messaging/accept",b=570,c=375;gfc_0l(a,gfc_h(b),gfc_h(c));return gfc_d};gfc_7[gfc_].Eq=function(){this.ja();this.z("block-member")};gfc_7[gfc_].Gq=function(){this.On(this.d[gfc_s].viewer)};
gfc_7[gfc_].tv=function(a){this.Qf();a={profile:a};var b=gfc_U("inviteMessage");if(b)a.message=gfc_8e(b);this.render(["sendFriendRequest"],"profile",a)};gfc_7[gfc_].to=function(a){this.Qf();this.qj(a)};gfc_7[gfc_].um=function(a,b,c){c=c||gfc_d;this.d[gfc_s].friendRequests=gfc_Jd(a.friendRequests,gfc_Ad);b["next-view"]=this.d[gfc_s].friendRequests[gfc_4a]()>0?"friend-requests":"faces";c||gfc_Ml("friend")};
gfc_7[gfc_].Mt=function(a){this.d[gfc_s][gfc_G].sites=a.get("profileSites")[gfc_t]();this.d[gfc_s][gfc_G].friends=a.get("friends")[gfc_t]()};gfc_7[gfc_].vq=function(){return this.mw};gfc_7[gfc_].W=function(){this.xx.rebuild();this.fo();gfc_e[gfc_Ta].adjustHeight()};gfc_7[gfc_].ft=function(a){return a=gfc_V("span",{"class":"fc-cap-link-big"},gfc_V("a",{"class":"fc-cap-link-big"},this.e.MSG_OPTIONS),a.Qg())};
gfc_7[gfc_].et=function(){var a=[];a[a[gfc_o]]=gfc_V("div",{"class":"goog-menuitem menuaction-settings"},this.e.MSG_SITE_SETTINGS);a[a[gfc_o]]=this.isSocialShareEnabled?gfc_V("div",{"class":"goog-menuitem menuaction-share"},this.e.MSG_MEMBERS_SHARE):gfc_V("div",{"class":"goog-menuitem menuaction-invite"},this.e.MSG_INVITE_FRIENDS);if(this.d[gfc_s].isViewerAdmin&&!this.Nb())a[a[gfc_o]]=gfc_V("div",{"class":"goog-menuitem menuaction-manage"},this.e.MSG_MANAGE);a[a[gfc_o]]=gfc_V("div",{"class":"goog-menuitem menuaction-signout"},
this.lb.signOutPrompt||this.e.MSG_SIGN_OUT);a[a[gfc_o]]=gfc_V("div",{"class":"goog-menuseparator fc-menuseparator-line"});a[a[gfc_o]]=gfc_V("div",{"class":"goog-menuitem menuaction-aboutfc"},gfc_V("span",{"class":"fc-small-menu-link"},this.e.MSG_ABOUT_FC));return a};
gfc_7[gfc_].gt=function(a){a[gfc_qb]();a=a[gfc_C].h()[gfc_2a];if(a[gfc_Sb]("menuaction-settings"))this.Bb();else if(a[gfc_Sb]("menuaction-invite"))this.invite();else if(a[gfc_Sb]("menuaction-share"))this.share();else if(a[gfc_Sb]("menuaction-signout"))this.signout();else if(a[gfc_Sb]("menuaction-manage"))this.Kq();else if(a[gfc_Sb]("menuaction-aboutfc")){a=gfc_i[gfc_Ya](gfc_Tl()+"/friendconnect");a[gfc__b]()}};
gfc_7[gfc_].Kq=function(){var a={},b=gfc_e[gfc_p][gfc_jb]().canvas;gfc_Ml("lightbox");gfc_e[gfc_p].requestNavigateTo(b,a);return gfc_d};var gfc_sm=function(a){for(var b={},c=0;c<a[gfc_o];++c)b[a[c]]=a[c];return b}(["HEIGHT","BORDER_COLOR","CONTENT_BG_COLOR","CONTENT_HEADLINE_COLOR","CONTENT_LINK_COLOR","CONTENT_SECONDARY_TEXT_COLOR","CONTENT_SECONDARY_LINK_COLOR","CONTENT_TEXT_COLOR","ENDCAP_BG_COLOR","ENDCAP_LINK_COLOR","ENDCAP_TEXT_COLOR","FACE_SIZE","NUMBER_ROWS"]);
gfc_7[gfc_].r=function(){var a=gfc_sm,b=[],c=0;gfc_fa(this.f(a.HEIGHT));if(this.Qh())b[c++]=this.j(".fc-thumbnail img {height:%spx;width:%spx}",this.f(a.FACE_SIZE));b[c++]=this.j(".fc-scroll-botnav, .fc-scroll, .fc-noscroll-botnav {height: %spx;}\n",this.Um);b[c++]=this.j(".fc-members,.fc-members-canvas {border-color: %s;}\n.fc-userpage-itemlist,.fc-userpage-itemlist-canvas,.fc-botcap-short { border-top-color: %s; }\n.fc-topcap,.fc-topverb,.fc-friendreq,.fc-friendreqs,.fc-timeframe { border-bottom-color: %s; }\n",
this.f(a.BORDER_COLOR));if(this.Af())if(this.el("profile"))b[c++]=".fc-topcap {height: "+this.slimTopCapHeight+"px;}\n";else if(this.Th())b[c++]=".fc-topcap {height: 0px;}\n";else b[c++]=".fc-topcap {height: "+this.tinyTopCapHeight+"px;}\n";if(this.Nb())b[c++]=".fc-userpic-caption {margin-left: 59px;}\n";else b[c++]=".fc-userpic-caption {margin-left: 40px;}\n";if(this.Th())b[c++]=".fc-topcap-color {background-color: white;}\n";else b[c++]=this.j(".fc-topcap-color {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));
if(this.ul())b[c++]=".fc-botcap-short {background-color: white;}\n";else b[c++]=this.j(".fc-botcap-short {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-topcap, .fc-botverb, .fc-topverb, .fc-botcap-short, .fc-header-sectitle, .fc-members-header {color: %s;}\n",
this.f(a.ENDCAP_TEXT_COLOR));b[c++]=this.j(".fc-botverb,.fc-topcap .fc-menutriangle-down, .fc-topcap .fc-menutriangle-up,.fc-topcap a, .fc-topcap a:active, .fc-topcap a:visited,.fc-topcap-link a, .fc-topcap-link a:active, .fc-topcap-link a:visited,.fc-cap-link-big a, .fc-cap-link-big a:active,.fc-left-verb a, .fc-left-verb a:active, .fc-left-verb a:visited,.fc-right-verb a, .fc-right-verb a:active, .fc-right-verb a:visited,.fc-subtle-botcap a, .fc-subtle-botcap a:active, .fc-subtle-botcap a:visited.fc-left-verb-canvas a, .fc-left-verb-canvas a:active, .fc-left-verb-canvas a:visited,.fc-right-verb-canvas a, .fc-right-verb-canvas a:active, .fc-right-verb-canvas a:visited {color: %s;}\n",
this.f(a.ENDCAP_LINK_COLOR));b[c++]=this.j(".fc-content-bg, .fc-subtle-botcap {background-color:%s;}\n",this.f(a.CONTENT_BG_COLOR));b[c++]=this.j(".fc-content a, .fc-content a:active, .fc-content a:visited,\n.fc-item-body a, .fc-item-body a:active, .fc-item-body a:visited,\n.fc-see-all a, .fc-see-all a:active, .fc-see-all a:visited,\n.fc-content-link a, .fc-content-link a:active, .fc-content-link a:visited,\n.fc-content-canvas a, .fc-content-canvas a:active, .fc-content-canvas a:visited {color: %s;}\n",
this.f(a.CONTENT_LINK_COLOR));b[c++]=this.j(".fc-members,.fc-members-canvas {color:%s;}\n",this.f(a.CONTENT_TEXT_COLOR));b[c++]=this.j(".fc-helpful,.fc-on-other-site,.fc-no-elements, .ot-activity-metadata {color:%s;}\n",this.f(a.CONTENT_SECONDARY_TEXT_COLOR));b[c++]=this.j(".fc-faded-link a, .fc-faded-link a:active, .fc-faded-link a:visited, .fc-faded-link-small a, .fc-faded-link-small a:active, .fc-faded-link-small a:visited {color: %s;}\n",this.f(a.CONTENT_SECONDARY_LINK_COLOR));b[c++]=this.j(".fc-sectitle {color: %s;}\n",
this.f(a.CONTENT_HEADLINE_COLOR));return gfc_7.i.r[gfc_D](this)+b[gfc_N]("\n")};gfc_P("goog.peoplesense.gadget.Members",gfc_7);gfc_P("goog.peoplesense.gadget.Members.start",gfc_7[gfc_F]);var gfc_tm=function(a,b,c){gfc_j.Collection[gfc_D](this,a[gfc_bb](c,c+b),c,a[gfc_o]);this.hx=a;this.ia=b};gfc_tm.inherits(gfc_j.Collection);gfc_tm[gfc_].all=function(){return this.hx};gfc_tm[gfc_].qb=function(){return this.ia};gfc_P("goog.peoplesense.gadget.Members.PagedCollection.prototype.all",gfc_tm[gfc_].all);
gfc_P("goog.peoplesense.gadget.Members.PagedCollection.prototype.getPageSize",gfc_tm[gfc_].qb);
